# Generated by Django 3.1.1 on 2020-09-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200906_1203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('first_name', 'last_name')},
        ),
    ]
