# Generated by Django 3.1 on 2020-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200906_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.CharField(blank=True, choices=[(0, 'kids'), (1, 'teens'), (2, 'adults')], default='G', max_length=7, null=True),
        ),
    ]
